### PR TITLE
#190 Add rawFormData option to allow handling raw FormData object

### LINKED ISSUE #190: Usage with Conform library (raw FormData input)
Hey, thanks for the great library. I would like to use it together with the [Conform](https://github.com/edmundhung/conform) library which is a great alternative to react-hook-form. However Conform library does its own transformation of FormData to json and schema validation (https://conform.guide/api/zod/parseWithZod). 

I suppose I would need something like `.input(undefined, { type: 'raw' })` which would simply pass the unprocessed input to the handler. There I would use the FormData and pass it to the Conform library.

### PR DESCRIPTION
**Pull request by Kamahl19**
closes #190

### CODE REVIEW

**Comment by IdoPesok** [comment]
Hi, sorry for the late response and thanks for putting together this PR with tests 🤩 

I am wondering if we should just have a method, `.inputFormData(Optional<{ type: "state" }>)` that basically takes care of the z.instanceof(FormData) and then the input arg is guaranteed to be form data. I think it is added overhead for people to have to think of writing z.custom if we are going to go down this solution and do it for them.

**Comment by Kamahl19** [comment]
Hey, no worries :) I am not sure I follow what you are suggesting. Imho the most flexible, easy to use and simple to understand solution would be the option to omit the `.input()` altogether. If you omit `.output()`, the output validation does not run. The same way we could omit `.input()`, skip the input validation and let the developer type the input themselves `.handle({ input }: {input: FormData})` or maybe via generic type. This gives the developer power to choose which features of ZSA to use e.g. only middleware, error handling, callbacks etc.

**Comment by IdoPesok** [comment]
Concur let's go with that. Can we update it to `skipInputParsing` and if that is set to true we will just return the input data without going through the input parser. Rather than being form data specific, let's make it general like you said.

**Comment by Kamahl19** [comment]
Are you suggesting `.input(undefined, {skipInputParsing: true})`? What I was suggesting was completely omitting the `.input()` method like `createServerAction().handler<FormData>(async ({ input }) => {})`, however that is quite a big change. Maybe more suitable for 1.0.0. So we could also the the input with a flag

**Comment by Kamahl19** [comment]
@IdoPesok I have rewritten it using the `skipInputParsing`. Please let me know if you believe the skip should happen at a different place in the `parseInputData` fn.

**Review by StanlieK — APPROVED** [review]

**Comment by Kamahl19** [comment]
@IdoPesok  Hey, sorry to bother you. Please let me know if there is anything I can do to move this forward. Thanks!

**Comment by IdoPesok** [comment]
Hi, can you run `npx changeset` and add a changeset. I will merge!

**Comment by Kamahl19** [comment]
@IdoPesok  done :)

**Pull request merged**
