### PR TITLE
useFormState and useActionState integration

### PR DESCRIPTION
**Pull request by IdoPesok**
In response to #63

This PR introduces `createActionStateHookFrom` that takes in either `useActionState` or `useFormState` and makes it super easy to use `zsa` actions.

```typescript
"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useActionState } from "react"
import { createActionStateHookFrom } from "zsa-react"
import { produceNewMessage } from "./actions"

const useAction = createActionStateHookFrom(useActionState)

export default function UseActionStateExample() {
  const [{ data, error }, submitAction, isPending] =
    useAction(produceNewMessage)

  return (
    <Card className="not-prose">
      <CardHeader>
        <CardTitle>Use Form State</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <form action={submitAction} className="flex flex-col gap-4">
          <Input name="name" placeholder="Enter your name..." />
          <Button>Create message</Button>
        </form>
        {isPending ? (
          <div>loading...</div>
        ) : data ? (
          <div>{data}</div>
        ) : error ? (
          <div>error : {JSON.stringify(error)}</div>
        ) : null}
      </CardContent>
    </Card>
  )
}
```

### CODE REVIEW

**Comment by IdoPesok** [comment]
This also addresses #29

**Comment by karlhorky** [comment]
Thanks for this!

One small piece of feedback:

- https://github.com/IdoPesok/zsa/issues/29#issuecomment-2141561452

**Comment by IdoPesok** [comment]
**new proposal**

in actions.ts:

```typescript
"use server"

import z from "zod"
import { createServerAction } from "zsa"

export const produceNewMessage = createServerAction()
  .input(
    z.object({
      name: z.string().min(5),
    }),
    {
      type: "state",
    }
  )
  .handler(async ({ input }) => {
    await new Promise((resolve) => setTimeout(resolve, 500))
    return "Hello, " + input.name
  })
```

in client component:

```typescript
"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { useActionState } from "react"
import { produceNewMessage } from "./actions"

export default function UseActionStateExample() {
  const [[data, err], submitAction, isPending] = useActionState(
    produceNewMessage,
    [null, null]
  )

  return (
    <Card className="not-prose">
      <CardHeader>
        <CardTitle>Use Form State</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        <form action={submitAction} className="flex flex-col gap-4">
          <Input name="name" placeholder="Enter your name..." />
          <Button>Create message</Button>
        </form>
        {isPending ? (
          <div>loading...</div>
        ) : data ? (
          <div>{data}</div>
        ) : err ? (
          <div>error : {JSON.stringify(err)}</div>
        ) : null}
      </CardContent>
    </Card>
  )
}
```

**Comment by IdoPesok** [comment]
closes #63 and closes #70

**Pull request merged**
