### PR TITLE
fix: 🔧Fix unusable request

### PR DESCRIPTION
**Pull request by EmiN364**

### CODE REVIEW

**Comment by IdoPesok** [comment]
Hi, can you please add a changeset 🙏 Thank you for contributing!

**Comment by EmiN364** [comment]
> Hi, can you please add a changeset 🙏 Thank you for contributing!

Just did!

**Comment by IdoPesok** [comment]
We may need some test updates. Seem to be failing now

**Comment by EmiN364** [comment]
> We may need some test updates. Seem to be failing now

Fixed! 🥒🎉

**Pull request merged**
